server {
    listen 80;
    server_name kd-studio.in www.kd-studio.in;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kd-studio.in www.kd-studio.in;

    ssl_certificate /etc/letsencrypt/live/kd-studio.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kd-studio.in/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
