server {
    listen 80 default_server;  # Make this the default server
    listen [::]:80 default_server;
    server_name kd-studio.in www.kd-studio.in;  # Only main domain

    # Redirect all HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl default_server;  # Make this the default server
    listen [::]:443 ssl default_server;
    server_name kd-studio.in www.kd-studio.in;  # Only main domain

    # SSL certificate files
    ssl_certificate /etc/letsencrypt/live/kd-studio.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kd-studio.in/privkey.pem;

    # SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Enable HSTS (HTTP Strict Transport Security) to enforce HTTPS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Prevent MIME type sniffing
    add_header X-Content-Type-Options nosniff;

    # Enable XSS protection
    add_header X-XSS-Protection "1; mode=block";

    # Disallow embedding this site in iframes
    add_header X-Frame-Options SAMEORIGIN;

    root /usr/share/nginx/html; # Path to your build directory
    index index.html;

    location / {
        try_files $uri $uri/ /index.html =404;
    }

    # Handle 404 errors gracefully
    error_page 404 /index.html;
}