server {
    listen 80;
    server_name kd-studio.in www.kd-studio.in;

    # Redirect HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kd-studio.in www.kd-studio.in;

    ssl_certificate /etc/letsencrypt/live/kd-studio.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kd-studio.in/privkey.pem;
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  10m;

    root /home/ubuntu/kd-studio-fe/dist; # Your build directory
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Additional configurations (e.g., SSL settings) can be added here
}
